### PR TITLE
feat(go): support go 1.23 and delve 1.23.1

### PR DESCRIPTION
**Pull request by henrymcconville**
* Upgrade Go to 1.23
* Upgrade Delve to 1.23.1
  * Update Delve patch based on Delve 1.23 codebase
* Add tests for go 1.21-1.23
* Remove unused tests for Go 1.13-1.17

### CODE REVIEW

**Review by plumpy — COMMENTED** [review]
Thanks for updating this! Can you rebase so that [this PR](https://github.com/GoogleContainerTools/container-debug-support/pull/141) is included and the integration tests will pass? Thanks!

**Comment by henrymcconville** [comment]
@plumpy done!

**Review by plumpy — APPROVED** [review]
Thanks!!

**Comment by mbana** [comment]
Thanks a lot!

Could you possibly make a release?

When will Skaffold (https://github.com/GoogleContainerTools/skaffold) pick up the changes and make a release?

**Comment by plumpy** [comment]
Yep, I created a release (accidentally jumped straight from 1.4 to 1.6... oops) and Skaffold should start using it automatically.

**Pull request merged**
